name: Wyvern Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run wyvern build
        run: |
          sudo bash wyvern build
      
      - uses: actions/upload-pages-artifact@v1.0.7
      - uses: actions/deploy-pages@v1.2.5

